### ISSUE TITLE
Linking error with Rust 1.14.0-nightly on i686 Windows

### ISSUE THREAD

**Issue by andreastt** [alexcrichton/port-of-rust#5]
We’re seeing a linking error with the i686-pc-windows-gnu target after rustc 1.14.0-nightly (86affcdf6 2016-09-28) was released: https://travis-ci.org/mozilla/geckodriver/jobs/163755702

Unfortunately port-of-rust is not pinned to a specific revision of Rust. The [i686-pc-windows-gnu/Dockerfile](https://github.com/alexcrichton/port-of-rust/blob/master/i686-pc-windows-gnu/Dockerfile) links to https://static.rust-lang.org/dist/rust-mingw-nightly-i686-pc-windows-gnu.tar.gz, which means we cannot simply pin to specific revision of port-of-rust.

cc @jgraham

**Comment by alexcrichton** [comment]
Ah I think that this ran into https://github.com/rust-lang/rust/issues/36793 which has since been fixed in master. If you use today's nightlies, do the problems go away?

It should be possible to switch the `Dockerfile` to stable as well!

**Comment by andreastt** [comment]
That doesn’t appear to be the case. This build was done using the latest Nightly through the port-of-rust Docker image just now: https://travis-ci.org/mozilla/geckodriver/jobs/164080633

**Comment by alexcrichton** [comment]
Oh bah, it looks like the [bug wasn't actually fixed](https://github.com/rust-lang/rust/issues/36793#issuecomment-2508036770)!

**Comment by alexcrichton** [comment]
FWIW this has now made its way into the nightlies, want to check again to see if the bug still reproduces?

**Comment by andreastt** [comment]
It looks like that fixed it: https://travis-ci.org/mozilla/geckodriver

Thank you!
